# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170317_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(upload_to=b''),
        ),
    ]
